version: '3.8'

networks:
  apps:
    driver: bridge
  db:
    driver: bridge

# run maven install before building images

services:

  bulletin-buddy-post-service:
    image: ase/bulletin-post-service
    build: bulletin-buddy-post-service
    container_name: postservice
    hostname: postservice
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - apps

  bulletin-buddy-authentication-service:
    image: ase/bulletin-authentication-service
    build: bulletin-buddy-authentication-service
    container_name: authenticationservice
    hostname: authenticationservice
    ports:
      - "8082:8082"
    restart: on-failure
    networks:
      - apps

  bulletin-buddy-comment-service:
    image: ase/bulletin-comment-service
    build: bulletin-buddy-comment-service
    container_name: commentservice
    hostname: commentservice
    ports:
      - "8083:8083"
    restart: on-failure
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DDL=false
    networks:
      - apps
      - db

  bulletin-buddy-client-service:
    image: ase/bulletin-client-service
    build: bulletin-buddy-client-service/bulletin-buddy-client-service-app
    container_name: clientservice
    hostname: clientservice
    ports:
      - "8085:8085"
    restart: on-failure
    networks:
      - apps

  gateway:
    image: ase/bulletin-gateway
    build: bulletin-buddy-gateway
    networks:
      - apps
    ports:
      - '8080:8080'
    environment:
      - JAVA_TOOL_OPTIONS=-Dpostservice.url=http://postservice:8081 -Dauthenticationservice.url=http://authenticationservice:8082 -Dclientservice.url=http://clientservice:8085 -Dcommentservice.url=http://commentservice:8083

  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db

volumes:
  local_pgdata:
  pgadmin-data: