version: '3'

# run maven install before building images

services:
  bulletin-buddy-frontend:
    image: ase/bulletin-buddy-frontend
    build: bulletin-buddy-frontend
    ports:
      - "8080:8080"
    restart: on-failure

  bulletin-buddy-offer-service:
    image: ase/bulletin-offer-service
    build: bulletin-buddy-offer-service
    ports:
      - "8081:8081"
    restart: on-failure

  bulletin-buddy-comment-service:
    image: ase/bulletin-comment-service
    build: bulletin-buddy-comment-service
    ports:
      - "8082:8082"
    restart: on-failure

  bulletin-buddy-authentication-service:
    image: ase/bulletin-authentication-service
    build: bulletin-buddy-authentication-service
    ports:
      - "8083:8083"
    restart: on-failure