version: '3'

# run maven install before building images

services:
  bulletin-buddy-frontend:
    image: ase/bulletin-buddy-frontend
    build: bulletin-buddy-frontend
    ports:
      - "8080:8080"
    restart: on-failure # db might not be ready yet -> restart until it is

  bulletin-buddy-comment-service:
    image: ase/bulletin-comment-service
    build: bulletin-buddy-backend-service
    ports:
      - "8081:8081"
    restart: on-failure # db might not be ready yet -> restart until it is
