version: '3'

services:
  bulletin-buddy-frontend:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-client:pr-22
    ports:
      - "9000:80"
    restart: on-failure

  bulletin-buddy-post-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-post-service:pr-22
    ports:
      - "8081:8081"
    restart: on-failure

  bulletin-buddy-authentication-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-authentication-service:pr-22
    ports:
      - "8082:8082"
    restart: on-failure

  bulletin-buddy-comment-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-comment-service:pr-22
    ports:
      - "8083:8083"
    restart: on-failure
