version: '3'

# run maven install before building images
# run this file with the command:
#     docker-compose -f docker-compose.dev.yml up

services:
  bulletin-buddy-frontend:
    image: ase/bulletin-buddy-client
    build: bulletin-buddy-client
    ports:
      - "8080:80"
    restart: on-failure

  bulletin-buddy-post-service:
    image: ase/bulletin-post-service
    build: bulletin-buddy-post-service
    ports:
      - "8081:8081"
    restart: on-failure

  bulletin-buddy-authentication-service:
    image: ase/bulletin-authentication-service
    build: bulletin-buddy-authentication-service
    ports:
      - "8082:8082"
    restart: on-failure

  bulletin-buddy-comment-service:
    image: ase/bulletin-comment-service
    build: bulletin-buddy-comment-service
    ports:
      - "8083:8083"
    restart: on-failure
