version: '3'

networks:
  apps:
    driver: bridge
  db:
    driver: bridge

volumes:
  postgres-database:
    driver: local
  pg-data:
  pgadmin-data:

services:

  gateway:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-gateway:0.1.0
    container_name: gateway
    networks:
      - apps
    ports:
      - '8080:8080'
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -Dpostservice.url=http://postservice:8081
        -Dauthenticationservice.url=http://authenticationservice:8082
        -Dcommentservice.url=http://commentservice:8083
        -Dclientservice.url=http://clientservice:8085

  bulletin-buddy-post-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-post-service:0.1.0
    container_name: post-service
    hostname: postservice
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/postgres_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DDL=false
    networks:
      - apps
      - db

  bulletin-buddy-authentication-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-authentication-service:0.1.0
    container_name: authentication-service
    hostname: authenticationservice
    ports:
      - "8082:8082"
    restart: on-failure
    networks:
      - apps

  bulletin-buddy-comment-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-comment-service:0.1.0
    container_name: comment-service
    hostname: commentservice
    ports:
      - "8083:8083"
    restart: on-failure
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/postgres_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DDL=false
    networks:
      - apps
      - db

  bulletin-buddy-client-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-client-service:0.1.0
    container_name: client-service
    hostname: clientservice
    ports:
      - "8085:8085"
    restart: on-failure
    networks:
      - apps

  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data
    expose:
      - "5433"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    command: -p 5433
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db

  postgres-database:
    image: postgres:15.1-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-database:/var/lib/postgresql/data