version: '3'

networks:
  apps:
    driver: bridge

# run maven install before building images

services:

  bulletin-buddy-post-service:
    image: ase/bulletin-post-service
    build: bulletin-buddy-post-service
    container_name: postservice
    hostname: postservice
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - apps

  bulletin-buddy-authentication-service:
    image: ase/bulletin-authentication-service
    build: bulletin-buddy-authentication-service
    container_name: authenticationservice
    hostname: authenticationservice
    ports:
      - "8082:8082"
    restart: on-failure
    networks:
      - apps

  bulletin-buddy-comment-service:
    image: ase/bulletin-comment-service
    build: bulletin-buddy-comment-service
    container_name: commentservice
    hostname: commentservice
    ports:
      - "8083:8083"
    restart: on-failure
    networks:
      - apps

  bulletin-buddy-client-service:
    image: ase/bulletin-client-service
    build: bulletin-buddy-client-service/bulletin-buddy-client-service-app
    container_name: clientservice
    hostname: clientservice
    ports:
      - "8085:8085"
    restart: on-failure
    networks:
      - apps

  gateway:
    image: ase/bulletin-gateway
    build: bulletin-buddy-gateway
    networks:
      - apps
    ports:
      - '8080:8080'
    environment:
      - JAVA_TOOL_OPTIONS=-Dpostservice.url=http://postservice:8081 -Dauthenticationservice.url=http://authenticationservice:8082 -Dclientservice.url=http://clientservice:8085 -Dcommentservice.url=http://commentservice:8083
