version: '3'

networks:
  apps:
    driver: bridge

volumes:
  postgres-database:
    driver: local

services:

  gateway:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-gateway:pr-22
    container_name: gateway
    networks:
      - apps
    ports:
      - '8080:8080'
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -Dpostservice.url=http://postservice:8081
        -Dauthenticationservice.url=http://authenticationservice:8082
        -Dcommentservice.url=http://commentservice:8083
        -Dclientservice.url=http://clientservice:8085

  bulletin-buddy-post-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-post-service:0.1.0
    container_name: post-service
    hostname: postservice
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - apps

  bulletin-buddy-authentication-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-authentication-service:0.1.0
    container_name: authentication-service
    hostname: authenticationservice
    ports:
      - "8082:8082"
    restart: on-failure
    networks:
      - apps

  bulletin-buddy-comment-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-comment-service:0.1.0
    container_name: comment-service
    hostname: commentservice
    ports:
      - "8083:8083"
    restart: on-failure
    networks:
      - apps

  bulletin-buddy-client-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-client-service:0.1.0
    container_name: client-service
    hostname: clientservice
    ports:
      - "8085:8085"
    restart: on-failure
    networks:
      - apps

  postgres-database:
    image: postgres:15.1-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-database:/var/lib/postgresql/data
