version: '3'

# run maven install before building images

services:
  bulletin-buddy-frontend:
    image: ase/bulletin-buddy-client
    build: bulletin-buddy-client
    ports:
      - "8080:80"
    restart: on-failure

  bulletin-buddy-offer-service:
    image: ase/bulletin-offer-service
    build: bulletin-buddy-offer-service
    ports:
      - "8081:8081"
    restart: on-failure

  bulletin-buddy-authentication-service:
    image: ase/bulletin-authentication-service
    build: bulletin-buddy-authentication-service
    ports:
      - "8082:8082"
    restart: on-failure

  bulletin-buddy-comment-service:
    image: ase/bulletin-comment-service
    build: bulletin-buddy-comment-service
    ports:
      - "8083:8083"
    restart: on-failure
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
