version: '3'

networks:
  apps:
    driver: bridge
  db:
    driver: bridge

volumes:
  postgres-database:
    driver: local
  pg-data:
  pgadmin-data:
  consul_config_data:
  consul_data:

services:

  gateway:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-gateway:1.1.0
    container_name: gateway
    networks:
      - apps
    ports:
      - '8080:8080'
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -Dspring.cloud.consul.host=consul_container
    depends_on:
      - consul

  bulletin-buddy-post-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-post-service:1.1.0
    hostname: postservice
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -Dspring.cloud.consul.host=consul_container
        -Dspring.cloud.consul.port=8500
        -Dspring.datasource.url=jdbc:postgresql://db:5433/postgres_db
        -Dspring.datasource.username=root
        -Dspring.datasource.password=root
        -Dspring.jpa.hibernate.ddl.auto=update
        -Dspring.jpa.hibernate.ddl=false
    restart: on-failure
    depends_on:
      - consul
      - db
    networks:
      - apps
      - db
    deploy:
      mode: replicated
      replicas: 2

  bulletin-buddy-authentication-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-authentication-service:1.1.0
    hostname: authenticationservice
    restart: on-failure
    depends_on:
      - consul
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -Dspring.cloud.consul.host=consul_container
        -Dspring.cloud.consul.port=8500
    networks:
      - apps
    deploy:
      mode: replicated
      replicas: 1

  bulletin-buddy-comment-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-comment-service:1.1.0
    hostname: commentservice
    restart: on-failure
    depends_on:
      - db
      - consul
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -Dspring.cloud.consul.host=consul_container
        -Dspring.cloud.consul.port=8500
        -Dspring.datasource.url=jdbc:postgresql://db:5433/postgres_db
        -Dspring.datasource.username=root
        -Dspring.datasource.password=root
        -Dspring.jpa.hibernate.ddl.auto=update
        -Dspring.jpa.hibernate.ddl=false
    networks:
      - apps
      - db
    deploy:
      mode: replicated
      replicas: 2

  bulletin-buddy-client-service:
    image: ghcr.io/salvatoreriefolo/bulletin-buddy-client-service:1.1.0
    hostname: clientservice
    restart: on-failure
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -Dspring.cloud.consul.host=consul_container
        -Dspring.cloud.consul.port=8500
    networks:
      - apps
    depends_on:
      - consul
    deploy:
      mode: replicated
      replicas: 1

  consul:
    image: consul:1.9.5
    container_name: consul_container
    hostname: consul_container
    ports:
      - '8500:8500'
    networks:
      - apps
    volumes:
      - consul_config_data:/consul/config
      - consul_data:/consul/data
    command: agent -server -dev -ui -ui-content-path=/devops/consul/ui -bootstrap-expect=1 -data-dir=/consul/data -config-dir=/consul/data -client=0.0.0.0

  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data
    expose:
      - "5433"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    command: -p 5433
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db

  postgres-database:
    image: postgres:15.1-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-database:/var/lib/postgresql/data