server:
  port: 8080

spring.application:
  name: gateway

spring.cloud.service-registry:
  auto-registration:
    enabled: false

spring.cloud.config:
  enabled: false

spring.cloud:
  compatibility-verifier:
    enabled: false
  consul:
    config:
      enabled: false
    discovery:
      enabled: true

spring.cloud.loadbalancer:
  health-check:
    repeat-health-check: true
    refetch-instance: true
    retry:
      enabled: true
      maxRetriesOnSameServiceInstance: 5

logging:
  level:
    root: INFO
    org:
      springframework:
        context:
          support: WARN
        cloud:
          gateway: TRACE

spring.cloud.gateway:
  routes:
    - id: postservice
      uri: lb://post-service
      predicates:
        - Path=/postservice/**
      filters:
        - RewritePath=/postservice/(?<path>.*), /$\{path}

    - id: authenticationservice
      uri: lb://authentication-service
      predicates:
        - Path=/authenticationservice/**
      filters:
        - RewritePath=/authenticationservice/(?<path>.*), /$\{path}

    - id: commentservice
      uri: lb://comment-service
      predicates:
        - Path=/commentservice/**
      filters:
        - RewritePath=/commentservice/(?<path>.*), /$\{path}

    - id: clientservice
      uri: lb://client-service
      predicates:
        - Path=/clientservice/**
      filters:
        - RewritePath=/clientservice/(?<path>.*), /$\{path}

    - id: default
      uri: lb://client-service
      predicates:
        - Path=/**
      filters:
        - RewritePath=/clientservice/(?<path>.*), /$\{path}


