DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS POST;

CREATE TABLE POST (
  ID uuid NOT NULL,
  TITLE varchar(200),
  BODY varchar(400),
  POSTER_EMAIL varchar(200),
  TYPE varchar(255),
  CREATION_TIMESTAMP TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE COMMENT (
  ID uuid NOT NULL,
  POST_ID uuid NOT NULL,
  CONTENT varchar(400),
  POSTER_EMAIL varchar(200),
  CREATION_TIMESTAMP TIMESTAMP,
  PRIMARY KEY (ID),
  CONSTRAINT FK_POST_ID
      FOREIGN KEY(POST_ID)
  	  REFERENCES POST(ID)
);
